### ISSUE TITLE
Wiz is broken in linux

### ISSUE THREAD

**Issue by undisbeliever** [wiz-lang/wiz#56] opened 2019-08-27 23:06 UTC
The latest master (1c152d0) is broken in Linux.

On ArchLinux with both g++ (9.1.0) and clang++ (8.0.1) wiz will only output the cartridge header and nothing else.
```
.-(~/repo/snes/maze-runner/wiz/examples/nes/hello)------------(dev@deadlocked)-
`--> sh build
* wiz: version 0.1.2 (alpha)
>> Parsing...
>> Compiling...
>> Writing ROM...
>> Wrote to "hello.nes".
* wiz: Done.
.-(~/repo/snes/maze-runner/wiz/examples/nes/hello)------------(dev@deadlocked)-
`--> hexdump hello.nes
0000000 454e 1a53 0000 0000 0000 0000 0000 0000
0000010
```
<br/>

Ironically it appears the source of the bug is caught as a compiler warning:
```
g++ -D_POSIX_SOURCE -Os -std=c++17 -MMD -Wall -Wextra -Werror -Wno-error=unused-variable -Wno-error=unused-result -Wno-error=unused-parameter -Wno-error=unused-function -Wno-error=unused-value -Wold-style-cast -Wnon-virtual-dtor -fno-exceptions -fno-rtti -c -o src/wiz/wiz.o src/wiz/wiz.cpp -Isrc
In file included from src/wiz/wiz.cpp:14:
src/wiz/format/format.h: In constructor ‘wiz::FormatContext::FormatContext(wiz::Report*, wiz::StringPool*, const wiz::Config*, wiz::StringView, wiz::ArrayView<const wiz::Bank*>)’:
src/wiz/format/format.h:22:36: warning: unused parameter ‘banks’ [-Wunused-parameter]
   22 |             ArrayView<const Bank*> banks)
      |             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
g++ -D_POSIX_SOURCE -Os -std=c++17 -MMD -Wall -Wextra -Werror -Wno-error=unused-variable -Wno-error=unused-result -Wno-error=unused-parameter -Wno-error=unused-function -Wno-error=unused-value -Wold-style-cast -Wnon-virtual-dtor -fno-exceptions -fno-rtti -c -o src/wiz/ast/expression.o src/wiz/ast/expression.cpp -Isrc
```
<br/>

The following patch fixes the bug on my system:
``` diff
diff --git a/src/wiz/format/format.h b/src/wiz/format/format.h
index a2e6ea2..1a1c162 100644
--- a/src/wiz/format/format.h
+++ b/src/wiz/format/format.h
@@ -23,7 +23,8 @@ namespace wiz {
         : report(report),
         stringPool(stringPool),
         config(config),
-        outputName(outputName) {}
+        outputName(outputName),
+        banks(banks){}
 
         Report* report;
         StringPool* stringPool;
```

**Comment by Bananattack** [comment] 2019-08-28 23:54
Doh! this was a good catch, looks like I committed a fix yesterday that did the same thing. Still thanks for this submission! Banks should be correctly passed along to the format handlers now.

Also unrelated to this particular issue, but, my build yesterday also broke the bit-flags wrapper class I made. I've just fixed that today... Hopefully that's the last of the bigger multi-file refactors for a bit, but it results in much better inlining of the BitFlags type so that it's on par with directly using the bitwise ops, no function calls in the disassembly now. 

Closing for now, but let me know if you run into any other problems.

**Comment by undisbeliever** [comment] 2019-08-29 00:18
@Bananattack It's still broken

```
g++ -D_POSIX_SOURCE -Os -std=c++17 -MMD -Wall -Wextra -Werror -Wno-error=unused-variable -Wno-error=unused-result -Wno-error=unused-parameter -Wno-error=unused-function -Wno-error=unused-value -Wold-style-cast -Wnon-virtual-dtor -fno-exceptions -fno-rtti -c -o src/wiz/wiz.o src/wiz/wiz.cpp -Isrc
In file included from src/wiz/wiz.cpp:5:
src/wiz/ast/statement.h:10:10: fatal error: wiz/ast/qualifiers.h: No such file or directory
   10 | #include <wiz/ast/qualifiers.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:100: src/wiz/wiz.o] Error 1
```

**Comment by Bananattack** [comment] 2019-08-29 00:22
Argh, I forgot to commit a file in that commit... try now! *crossing fingers*

**Comment by undisbeliever** [comment] 2019-08-29 00:33
Sorry, still broken:

wiz 3e4dfe0
```
.-(~/repo/snes/maze-runner)-----------(dev@deadlocked)-
`--> make
wiz/bin/wiz -I src src/main.wiz -o maze-runner.sfc
* wiz: version 0.1.2 (alpha)
>> Parsing...
>> Compiling...
game.wiz:331: error: bank-byte access `#:` is not defined for provided operand type `*[u8; 64]`
game.wiz:587: error: bank-byte access `#:` is not defined for provided operand type `*[u8; 64]`
game.wiz:599: error: bank-byte access `#:` is not defined for provided operand type `*const [u8; 16384]`
* wiz: failed with 3 error(s).
make: *** [GNUmakefile:13: maze-runner.sfc] Error 1
```

**Comment by Bananattack** [comment] 2019-08-29 01:34
Sorry :( I am going to try to investigate a bit more, but if I can't figure this out soon I am going to revert these changes.  It seems like `#:` bank-byte access isn't working because it thinks the pointers aren't far pointers... Something must be incorrectly propagating the `far` qualifier somewhere. Will try to have a better update on this soon.

**Comment by undisbeliever** [comment] 2019-08-29 01:38
That's ok, I can always use an earlier release for now.

**Comment by Bananattack** [comment] 2019-08-29 02:11
Okay. I've committed a fix to address a regression in the `far &` operator. In some local tests, it fixed some issues where `far` wasn't being carried across to pointers when it should have been. That is most likely the cause but only one way to know for sure.

**Comment by undisbeliever** [comment] 2019-08-29 02:25
Thanks, that fixed it.

**Closed** 2019-08-29 02:26 UTC
