### ISSUE TITLE
macOS: Crash when compiling most examples

### ISSUE THREAD

**Issue by MichaelBuckley** [wiz-lang/wiz#119] opened 2021-02-19 20:33 UTC
Hello. Although I am filing this as an issue, I am willing to do the work to fix this and submit a pull request once I have a better understanding of the compiler code.

The compiler crashes on an assert when building most of the examples. I have debugger output with a stack trace that I will attach to this ticket, but the crash occurs on the assert at optional.h line 117.

All examples cause this crash except:

- gb/snake
- gb/xzone
- gg/hello
- msx/hello
- nes/hello
- pce/hello

This crash occurs with the code at HEAD, but using git bisect, I was able to find that it was introduced at commit 5e9fc769eb20f97e7315b2f419c504cd81548c9c

[wizdebug.txt](https://github.com/wiz-lang/wiz/files/6012777/wizdebug.txt)

**Comment by Bananattack** [comment] 2021-02-23 19:02
Hi thanks for this detailed report and bisecting to find the commit that failed! I'll try to compile on my macbook air when I get a free moment, but if you think you can look at this sooner, please feel free!

Usually when I've encountered this sort of problem, it had to do with calling std::move() on a function argument, and referencing that same argument in another spot in the call. Basically, C++ doesn't standardize an order for arguments to be evaluated, and leaves this unspecified. So there have been occasional issues that only show up when the argument evaluation issue is different...

Looking from the wizdebug.log, the problem is in `compiler.cpp:2079` of the version that was built there -- namely, `operand` is passed like `std::move(operand)`, but it also accesses `operand->info->qualifiers` within the same make unique call. Since moving will null out the operand pointer in the process, this results in a problem if the move gets evaluated before the other member .

A fix might be to go like this, to force things to be accessed before move:

```
                        const auto qualifiers = operand->info->qualifiers;
                        return makeFwdUnique<const Expression>(
                            Expression::UnaryOperator(unaryOperator.op, std::move(operand)), expression->location,
                            ExpressionInfo(context, std::move(resultType), qualifiers));
```

I don't know if this is the only issue with the particular crash you're seeing, but this should be a good start.

**Comment by MichaelBuckley** [comment] 2021-02-23 20:00
That change did the trick! After making that change, I was able to compile all of the examples without issue.

Your explaination made sense. I should have thought of that myself, but I was too distracted trying to absorb the entirety of what the compiler was doing.

It looks like clang-tidy has a check for using an object after a move, but I don't know if it's smart enough to catch argument evaluation order issues. I'll give it a try on the current code and report back if it catches the issue.

https://clang.llvm.org/extra/clang-tidy/checks/bugprone-use-after-move.html

**Comment by MichaelBuckley** [comment] 2021-02-23 21:10
It looks like clang-tidy does catch it, along with a few others.

```
clang-tidy src/wiz/compiler/compiler.cpp --checks='bugprone-use-after-move' -- -Isrc
5 warnings generated.
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:499:51: warning: 'reducedValueExpression' used after it was moved [bugprone-use-after-move]
                        items.push_back(std::move(reducedValueExpression));
                                                  ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:499:31: note: move occurred here
                        items.push_back(std::move(reducedValueExpression));
                              ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:499:51: note: the use happens in a later loop iteration than the move
                        items.push_back(std::move(reducedValueExpression));
                                                  ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:2079:76: warning: 'operand' used after it was moved [bugprone-use-after-move]
                            ExpressionInfo(context, std::move(resultType), operand->info->qualifiers));
                                                                           ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:2078:73: note: move occurred here
                            Expression::UnaryOperator(unaryOperator.op, std::move(operand)), expression->location,
                                                                        ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:2079:76: note: the use and move are unsequenced, i.e. there is no guarantee about the order in which they are evaluated
                            ExpressionInfo(context, std::move(resultType), operand->info->qualifiers));
                                                                           ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:5221:21: warning: Value stored to 'tailCall' is never read [clang-analyzer-deadcode.DeadStores]
                    tailCall = false;
                    ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:5221:21: note: Value stored to 'tailCall' is never read
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:5247:25: warning: Value stored to 'valid' is never read [clang-analyzer-deadcode.DeadStores]
                        valid = emitFunctionIr(definition, function->location);
                        ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:5247:25: note: Value stored to 'valid' is never read
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:6115:17: warning: Forming reference to null pointer [clang-analyzer-core.NonNullParamChecker]
                report->error("branch conditional must be a boolean expression, but got expression of type `" + getTypeName(condition->info->type.get()) + "`", destination->location);
                ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:6012:9: note: Control jumps to the 'default' case at line 6103
        switch (kind) {
        ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:6103:22: note:  Execution continues on line 6106
            default: break;
                     ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:6106:13: note: Assuming 'destination' is null
        if (destination) {
            ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:6106:9: note: Taking false branch
        if (destination) {
        ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:6113:13: note: Assuming 'condition' is non-null
        if (condition) {
            ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:6113:9: note: Taking true branch
        if (condition) {
        ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:6114:18: note: Calling 'Compiler::isBooleanType'
            if (!isBooleanType(condition->info->type.get())) {
                 ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:2862:38: note: Left side of '&&' is false
        return definition != nullptr && definition->kind == DefinitionKind::BuiltinBoolType;
                                     ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:2862:9: note: Returning zero, which participates in a condition later
        return definition != nullptr && definition->kind == DefinitionKind::BuiltinBoolType;
        ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:6114:18: note: Returning from 'Compiler::isBooleanType'
            if (!isBooleanType(condition->info->type.get())) {
                 ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:6114:13: note: Taking true branch
            if (!isBooleanType(condition->info->type.get())) {
            ^
/Users/buckley/Projects/wiz/src/wiz/compiler/compiler.cpp:6115:17: note: Forming reference to null pointer
                report->error("branch conditional must be a boolean expression, but got expression of type `" + getTypeName(condition->info->type.get()) + "`", destination->location);
```

**Comment by MichaelBuckley** [comment] 2021-02-23 22:05
Looks like there are also a few in wdc65816_platform.cpp. I've attached the full report.

[clang-tidy-output.txt](https://github.com/wiz-lang/wiz/files/6032055/clang-tidy-output.txt)

**Comment by Bananattack** [comment] 2021-02-25 02:33
Wow! Thanks for attaching this, this is super handy! I'll try to get clang-tidy set up to check some stuff like that and clean these issues from the code. If there are ever automated builds setup for Wiz, this sort of check on commits would be very useful to run to prevent these kinds of bugs from slipping into the code.

I've been trying to find time to catch up on this and other bugs when settle down a little bit more on my end.

**Comment by Bananattack** [comment] 2021-02-28 08:48
Hey! I just committed a fix to address a bunch of these clang-tidy reports. Can you test this out on your end potentially to see if this works on your Mac? I would like to test but I don't have my Macbook Air setup at the moment -- it will take me a little more time to test if I have to confirm it myself.

**Comment by MichaelBuckley** [comment] 2021-02-28 18:14
Sure. I'm happy to test out these kinds of changes on macOS.

I pulled the latest, and found that there are a few compiler errors that got introduced. Most of them are along the lines of:

```
src/wiz/ast/qualifiers.h:19:5: error: GCC does not allow 'always_inline' attribute in this position on a function definition [-Werror,-Wgcc-compat]
    WIZ_BITWISE_OVERLOADS(Qualifiers)
    ^
src/wiz/utility/bitwise_overloads.h:9:5: note: expanded from macro 'WIZ_BITWISE_OVERLOADS'
    WIZ_MAYBE_UNUSED_FORCE_INLINE(T operator ~(T value)) { \
    ^
src/wiz/utility/macros.h:9:73: note: expanded from macro 'WIZ_MAYBE_UNUSED_FORCE_INLINE'
#define WIZ_MAYBE_UNUSED_FORCE_INLINE(x) inline static x __attribute__((always_inline)) __attribute__((unused))
```

I'll try to get these fixed and submit an MR in the next couple days.

**Comment by MichaelBuckley** [comment] 2021-02-28 18:58
Fixing hte compilation ended up being simpelr than I feared. I submitted a PR at https://github.com/wiz-lang/wiz/pull/121 Feel free to reject it and replace it with your own fix if you prefer. The cause was that GCC can't abide `__attribute__` between a function signasture and the opening brace. It needs to go before the signature.

As for the changes themselves, they appear to be working. I compiled the snes/hello example, which was previously crashing on compile, and the output ROM looks good.

**Comment by Bananattack** [comment] 2021-02-28 19:05
Sounds good! 

I just made some changes and hopefully the build is fixed now! I tried building on Windows with Visual Studio, clang + clang-tidy, GCC and emscripten. Hopefully this catches the issue that you were seeing on Mac OS X. But sounds like we're close to being able to close this, some compiler compatibility stuff aside!

**Comment by Bananattack** [comment] 2021-02-28 19:20
Oops, I didn't see that you had written a PR too! I just saw the error
message and did a quick fix. I am away from the computer again for now but
let me know and I'll try to look if there's anything missing that the pr
does. Thanks a bunch for the help reporting this and helping to track down
these issues!

**Comment by Bananattack** [comment] 2021-02-28 20:17
Okay, I had a chance to review the PR you did and it appears to fix the same thing in `macros.h` -- this macro appeared to be necessary to suppress some warnings about unused operator overloads, that were preventing clang-tidy from getting to do actual code analysis (because it would stop after those warnings).

Since our changes do a similar fix, and you were able to build the examples on a Mac, I think we're good! Going to close this issue :)

**Closed by Bananattack** 2021-02-28 20:17 UTC

**Comment by MichaelBuckley** [comment] 2021-03-01 04:27
Thanks for taking care of it! And no worries about the crossed paths there. I had to step away from the computer shortly after my last commen on this thread.

Please feel free to reach out to me at any time if you need assistance with Mac testing.
